### ISSUE TITLE
Feature request: Autofocus on first selection.

### ISSUE THREAD

**Issue by eightbitswide** [nihirash/Agon-MOS-Tools#1]
I noticed that when I use gopher in my desktop it auto focuses the selection to the first available option on the page.  On the Agon, the pointer simply starts at the top of the page.  Is there any chance you could incorporate that feature into new versions?

Thanks
8b

**Comment by nihirash** [comment]
Looks like not most complex thing to implement!

I'll try implement this in next release.

**Comment by nihirash** [comment]
Try this version: https://github.com/nihirash/Agon-MOS-Tools/tree/first_link/esp8266/snail/bin
