### ISSUE TITLE
Feature Request: Download .BAS files in snail

### ISSUE THREAD

**Issue by astralaster** [nihirash/Agon-MOS-Tools#3]
Hi,

when I open a .BAS file with snail it displays the content. It would be great if there was an option to save it to disk.

**Comment by nihirash** [comment]
It shows only cause it have plain text data-type. If it will have binary data type it will be downloaded. 

But It's possible add routine for handling bas files as binary files.

**Comment by eightbitswide** [comment]
You may be able to add a line like :bas=9 to your gophermap file.  This would should make the gopher server set that file type to download instead of display.   I chose not to use it on my server for .bas files proving them for viewing and the .bbc files for downloading the files.

**Comment by nihirash** [comment]
You can find version that supports saving current buffer to disk here: https://github.com/nihirash/agon-snail

This issue is the same as: https://github.com/nihirash/Agon-MOS-Tools/issues/6
