### ISSUE TITLE
Ability to download ASCII files in Snail

### ISSUE THREAD

**Issue by jblang** [nihirash/Agon-MOS-Tools#6]
Currently, Snail prompts to download binary files but if a file is ASCII, it will display it, with no way to download.  This is especially inconvenient because there are a lot of ASCII .BAS files in agon gopherspace, but it is not possible to save them, so they have to be copied to the SD card by some other means. It would be great to add a menu item (and possible hotkey) to download the currently displayed file.

**Comment by nihirash** [comment]
You can find version that supports saving current buffer to disk here: https://github.com/nihirash/agon-snail
